version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/raw
hooks:
  BeforeInstall:
    - location: scripts-deploy/before-install.sh
  #AfterInstall:
  #  - location: scripts-deploy/npm-install.sh
  #    runas: ec2-user
  #    timeout: 300
  #ApplicationStart:
  #  - location: scripts/npm-start.sh
  #    runas: root
  #    timeout: 60
