version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/raw
hooks:
  BeforeInstall:
    - location: scripts-deploy/before-install.sh
  Install:
    - location: scripts-deploy/install.sh
  AfterInstall:
    - location: scripts-deploy/after-install.sh
      runas: ec2-user
      timeout: 300
  #ApplicationStart:
  #  - location: scripts/npm-start.sh
  #    runas: root
  #    timeout: 60
